apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager
  # - certificates
  - grafana
  - homarr
  - metallb
  - nextcloud
  - prometheus
  - routes
  # - traefik
