apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homarr-cert
  namespace: cert-manager
spec:
  dependsOn:
    - name: cert-manager
  secretName: homarr-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - homarr.totorolab.local
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nextcloud-cert
  namespace: cert-manager
spec:
  dependsOn:
    - name: cert-manager
  secretName: nextcloud-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - nextcloud.totorolab.local
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-cert
  namespace: cert-manager
spec:
  dependsOn:
    - name: cert-manager
  secretName: grafana-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - grafana.totorolab.local
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-cert
  namespace: cert-manager
spec:
  dependsOn:
    - name: cert-manager
  secretName: traefik-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - traefik.totorolab.local
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  dependsOn:
    - name: cert-manager
  acme:
    email: you@example.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
      - http01:
          ingress:
            class: traefik
