apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - homarr-helm-repository.yaml
  - traefik-helm-repository.yaml
  - metallb-helm-repository.yaml
  - certmanager-helm-repository.yaml
