apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: public-pool
  namespace: metallb
spec:
  dependsOn:
    - name: metallb
  addresses:
    - 192.168.10.240 - 192.168.4.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: public-l2-advertisement
  namespace: metallb
spec:
  dependsOn:
    - name: metallb
  ipAddressPools:
    - public-pool
